# █▀▄▀█ █▀█ █▄░█ █ ▀█▀ █▀█ █▀█ █▀
# █░▀░█ █▄█ █░▀█ █ ░█░ █▄█ █▀▄ ▄█
# ------------------------------------------------------
# Dynamic Monitor Configuration.
# Variables are sourced from config.env via install.sh logic.

# Syntax: monitor = name, res, offset, scale
monitor = $MONITOR_NAME, $MONITOR_RES, $MONITOR_POS, $MONITOR_SCALE
